/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RelationshipType = IDL.Variant({
  'pet' : IDL.Null,
  'romantic' : IDL.Null,
  'friend' : IDL.Null,
  'family' : IDL.Null,
});
export const PetType = IDL.Variant({
  'cat' : IDL.Null,
  'dog' : IDL.Null,
  'other' : IDL.Text,
  'bird' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const Pet = IDL.Record({
  'name' : IDL.Text,
  'emotionalSupportNotes' : IDL.Text,
  'petType' : PetType,
  'addedDate' : Time,
  'careSchedule' : IDL.Text,
});
export const Partner = IDL.Record({
  'name' : IDL.Text,
  'connectionDate' : Time,
  'relationshipType' : RelationshipType,
});
export const Relationship = IDL.Record({
  'owner' : IDL.Principal,
  'pets' : IDL.Vec(Pet),
  'lastUpdated' : Time,
  'createdDate' : Time,
  'partners' : IDL.Vec(Partner),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPartner' : IDL.Func([IDL.Text, IDL.Text, RelationshipType], [], []),
  'addPet' : IDL.Func(
      [IDL.Text, IDL.Text, PetType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRelationship' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllRelationships' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Relationship))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getRelationship' : IDL.Func([IDL.Text], [IDL.Opt(Relationship)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RelationshipType = IDL.Variant({
    'pet' : IDL.Null,
    'romantic' : IDL.Null,
    'friend' : IDL.Null,
    'family' : IDL.Null,
  });
  const PetType = IDL.Variant({
    'cat' : IDL.Null,
    'dog' : IDL.Null,
    'other' : IDL.Text,
    'bird' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const Pet = IDL.Record({
    'name' : IDL.Text,
    'emotionalSupportNotes' : IDL.Text,
    'petType' : PetType,
    'addedDate' : Time,
    'careSchedule' : IDL.Text,
  });
  const Partner = IDL.Record({
    'name' : IDL.Text,
    'connectionDate' : Time,
    'relationshipType' : RelationshipType,
  });
  const Relationship = IDL.Record({
    'owner' : IDL.Principal,
    'pets' : IDL.Vec(Pet),
    'lastUpdated' : Time,
    'createdDate' : Time,
    'partners' : IDL.Vec(Partner),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPartner' : IDL.Func([IDL.Text, IDL.Text, RelationshipType], [], []),
    'addPet' : IDL.Func(
        [IDL.Text, IDL.Text, PetType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRelationship' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllRelationships' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Relationship))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getRelationship' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Relationship)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };